name: ZY_Player_flutter
description: 免费影视资源播放

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization https://github.com/dart-lang/intl
  intl: ^0.16.1
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.2
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.10
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.24.1
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.3.3
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.7.10
  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.6.7+12
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.7
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^1.0.7
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.3.1+1
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.7.7
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.4.1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^5.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^4.3.2+2
  # 事件通知
  event_bus: ^1.1.1
  #json 序列化
  json_annotation: ^3.1.0
  #播放器
  fijkplayer: ^0.8.7
  #更新
  ota_update: ^2.4.1
  package_info: ^0.4.3+2
  flutter_update_dialog: ^1.0.0
  #动画
  flutter_staggered_animations: "^0.1.2"
  # 视频推送
  flutter_dlna: ^0.0.1+1
  #dialog
  giffy_dialog: 1.8.0
  #权限
  permission_handler: 5.0.1+1

  # 统计
  janalytics_fluttify: 0.3.2+1
  #二维码
  qr_flutter: 3.2.0
  image_pickers: 1.0.8+7

dev_dependencies:
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/home/
    - assets/images/state/

  fonts:
    - family: xuifont  #指定一个字体名
      fonts:
        - asset: assets/fonts/iconfont.ttf
